<?xml version="1.0"?>

<robot name = "tacocat_chassis" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find tacocat_description)/urdf/properties.xacro"/>
    <xacro:include filename="$(find tacocat_description)/urdf/chassis.xacro"/>
    <xacro:include filename="$(find tacocat_description)/urdf/wheel.xacro"/>
    <xacro:include filename="$(find tacocat_description)/urdf/camera.xacro"/>
    <xacro:include filename="$(find tacocat_description)/urdf/laser.xacro"/>

    <xacro:chassis/>

    <xacro:tacocam/>

    <xacro:laser/>

    <xacro:wheel 
        name="left" 
        translation="0 ${wheel_attached_point} 0" 
        rotation="0 0 0" 
        parent="base_link"
        rotate_wheel="${-Pi/2}"/>

    <xacro:wheel 
        name="right" 
        translation="0 ${-wheel_attached_point} 0" 
        rotation="0 0 0" 
        parent="base_link"
        rotate_wheel="${Pi/2}"/>


    <!-- Plugins below are from http://gazebosim.org/tutorials?tut=ros_gzplugins -->

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <!-- Plugin update rate in Hz -->
            <updateRate>100</updateRate>
            <!-- Name of left joint, defaults to `left_joint` -->
            <leftJoint>left_wheel_joint</leftJoint>
            <!-- Name of right joint, defaults to `right_joint` -->
            <rightJoint>right_wheel_joint</rightJoint>
            <!-- The distance from the center of one wheel to the other, in meters, defaults to 0.34 m -->
            <wheelSeparation>${wheel_attached_point*2}</wheelSeparation>
            <!-- Diameter of the wheels, in meters, defaults to 0.15 m -->
            <wheelDiameter>${wheel_radius*2}</wheelDiameter>
            <!-- Wheel acceleration, in rad/s^2, defaults to 0.0 rad/s^2 -->
            <wheelAcceleration>0.0</wheelAcceleration>
            <!-- Maximum torque which the wheels can produce, in Nm, defaults to 5 Nm -->
            <wheelTorque>5</wheelTorque>
            <!-- Topic to receive geometry_msgs/Twist message commands, defaults to `cmd_vel` -->
            <commandTopic>cmd_vel</commandTopic>
            <!-- Topic to publish nav_msgs/Odometry messages, defaults to `odom` -->
            <odometryTopic>odom</odometryTopic>
            <!-- Odometry frame, defaults to `odom` -->
            <odometryFrame>odom</odometryFrame>
            <!-- Robot frame to calculate odometry from, defaults to `base_footprint` -->
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <!-- Odometry source, 0 for ENCODER, 1 for WORLD, defaults to WORLD -->
            <odometrySource>0</odometrySource>
            <!-- Set to true to publish transforms for the wheel links, defaults to false -->
            <publishWheelTF>false</publishWheelTF>
            <!-- Set to true to publish transforms for the odometry, defaults to true -->
            <publishOdom>true</publishOdom>
            <!-- Set to true to publish sensor_msgs/JointState on /joint_states for the wheel joints, defaults to false -->
            <publishWheelJointState>true</publishWheelJointState>
            <!-- Set to true to swap right and left wheels, defaults to true -->
            <legacyMode>false</legacyMode>
        </plugin>
    </gazebo>



</robot>